#!/usr/bin/env python

import sys, os, shutil, subprocess, time, argparse
import numpy as np
import pandas as pd


def get_parameters():
    parser = argparse.ArgumentParser(description='Extract the two NIfTI images and submission ID, and use them to call process_data.py.')
    parser.add_argument('num',
                        help='NiftyWeb ID')
    parser.add_argument('image_1',
                        help='Initial scan')
    parser.add_argument('image_2',
                        help='Re-scan')
    args = parser.parse_args()
    return args

def main():
    num = args.num
    image_1 = os.path.basename(args.image_1)
    image_2 = os.path.basename(args.image_2)
    dir_data = os.path.dirname(args.image_1)

    # Send email notification of request
    mail = 'mutt -s "Request received for {}" stephanie.j.alley@gmail.com,jcohen@polymtl.ca,f.carrasco@ucl.ac.uk < /dev/null'.format(num)
    subprocess.check_call(mail, shell=True)
    
    os.chdir(dir_data)

    # Initiate processing script
    subprocess.call(["${SCT_DIR}/python/bin/python", "/home/niftyweb_sct/gm_challenge/process_data.py", "-i", image_1, image_2, "-n", num, "-o","{}_WMGM".format(num)])

    # Check for output files to return to user
    final_txt = os.path.join(dir_data + '/' + num + '_WMGM.txt')
    final_zip = os.path.join(dir_data + '/' + num + '_WMGM.zip')

    if (os.path.isfile(final_txt)) and (os.path.isfile(final_zip)):
	exit()

    done = 0
    while(done == 0):
        if (os.path.isfile(final_txt)) and (os.path.isfile(final_zip)):
            done = 1
        else:
            time.sleep(60)

if __name__ == "__main__":
    args = get_parameters()
    main()
